export default function PrivacyShield() {
  const guarantees = [
    {
      icon: "🧬",
      title: "No Biological Data Exposed",
      desc: "Cycle phase, symptoms, and all medical identifiers are fully stripped before this view is generated.",
    },
    {
      icon: "🔐",
      title: "Health Data Stays Private",
      desc: "All sensitive health inputs remain encrypted within the Personal Health Intelligence Engine only.",
    },
    {
      icon: "⚖️",
      title: "Ethically Compliant",
      desc: "This dashboard complies with dignity-first design principles. No inference of medical conditions is possible.",
    },
    {
      icon: "👁️",
      title: "What You See Is All There Is",
      desc: "Readiness indicators are the final abstracted output. No drill-down or raw data access exists at this level.",
    },
  ];

  return (
    <div className="rounded-2xl border border-emerald-500/20 bg-emerald-950/20 p-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-xl">
          🛡️
        </div>
        <div>
          <div className="text-base font-bold text-emerald-300">
            Privacy Shield — Engine 2 Guarantee
          </div>
          <div className="text-xs text-emerald-400/60 mt-0.5">
            This view is generated by the Risk Abstraction Engine
          </div>
        </div>
      </div>

      {/* Engine flow diagram */}
      <div className="mt-5 flex items-center gap-2 overflow-x-auto pb-2">
        {[
          { label: "Health Data", sub: "Engine 1", icon: "🏥", blocked: true },
          { label: "→", sub: "", icon: "", blocked: false, arrow: true },
          { label: "Computation", sub: "Engine 1.1", icon: "⚙️", blocked: true },
          { label: "→", sub: "", icon: "", blocked: false, arrow: true },
          { label: "Abstraction", sub: "Engine 2", icon: "🔒", blocked: false },
          { label: "→", sub: "", icon: "", blocked: false, arrow: true },
          { label: "Readiness", sub: "Engine 2.1", icon: "✅", blocked: false },
        ].map((step, i) => {
          if (step.arrow) {
            return (
              <div key={i} className="text-white/30 text-lg font-bold shrink-0">
                →
              </div>
            );
          }
          return (
            <div
              key={i}
              className={`
                shrink-0 rounded-xl border px-3 py-2 text-center min-w-[80px]
                ${step.blocked
                  ? "border-red-500/30 bg-red-950/30"
                  : "border-emerald-500/30 bg-emerald-950/30"}
              `}
            >
              <div className="text-lg">{step.icon}</div>
              <div className={`text-[10px] font-bold mt-1 ${step.blocked ? "text-red-300" : "text-emerald-300"}`}>
                {step.label}
              </div>
              <div className="text-[9px] text-white/30 mt-0.5">{step.sub}</div>
              {step.blocked && (
                <div className="text-[9px] text-red-400/70 mt-1">🚫 Hidden</div>
              )}
            </div>
          );
        })}
      </div>

      {/* Guarantee cards */}
      <div className="mt-5 grid grid-cols-1 sm:grid-cols-2 gap-3">
        {guarantees.map((g, i) => (
          <div
            key={i}
            className="flex items-start gap-3 rounded-xl border border-white/8 bg-white/4 p-3"
          >
            <div className="text-xl shrink-0 mt-0.5">{g.icon}</div>
            <div>
              <div className="text-xs font-bold text-white/80">{g.title}</div>
              <div className="text-[11px] text-white/40 mt-1 leading-relaxed">{g.desc}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Bottom stamp */}
      <div className="mt-5 flex items-center justify-between px-4 py-3 rounded-xl bg-emerald-900/20 border border-emerald-500/20">
        <div className="flex items-center gap-2">
          <span className="text-lg">✅</span>
          <span className="text-xs font-bold text-emerald-300">
            Privacy, Dignity & Ethical Compliance Verified
          </span>
        </div>
        <span className="text-[10px] text-emerald-400/50 font-mono">
          She Pulse Engine 2.1
        </span>
      </div>
    </div>
  );
}