import { useEffect, useState } from "react";
import { api } from "../api/api.js";
import ReadinessBadge from "../components/ReadinessBadge.jsx";
import PrivacyShield from "../components/PrivacyShield.jsx";
import TaskAdjustments from "../components/TaskAdjustments.jsx";
import Accommodations from "../components/Accommodations.jsx";

export default function WorkplaceDashboard({ profileId, onBack }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");

  useEffect(() => {
    if (!profileId) return;
    fetchWorkplace();
  }, [profileId]);

  async function fetchWorkplace() {
    setLoading(true);
    setErr("");
    try {
      const res = await api.get(`/workplace/${profileId}`);
      setData(res.data);
    } catch (e) {
      const detail = e?.response?.data?.detail;
      setErr(
        typeof detail === "string"
          ? detail
          : "Failed to load workplace readiness. Please complete a check-in first."
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="w-full min-h-screen bg-[#0a000f] text-white px-3 sm:px-6 lg:px-10 py-6 grid gap-4">

      {/* ── Navbar ── */}
      <div className="sticky top-3 z-40">
        <div className="w-full rounded-2xl border border-slate-800 bg-slate-900/80 backdrop-blur-md px-5 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="text-xl font-extrabold text-white">🏢 Workplace View</div>
            <span className="px-2 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs font-bold">
              Engine 2 + 2.1
            </span>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs text-white/30 hidden sm:block">
              Privacy-Safe • No Health Data
            </span>
            <button
              onClick={onBack}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 transition text-sm font-semibold"
            >
              ← Back to Dashboard
            </button>
          </div>
        </div>
      </div>

      {/* ── Content ── */}
      <div className="w-full max-w-[1200px] mx-auto grid gap-5">

        {/* ── Hero Header ── */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <div className="text-xs font-bold tracking-widest uppercase text-white/30 mb-2">
                She Pulse — Workplace Intelligence
              </div>
              <h1 className="text-3xl font-extrabold text-white">
                Employee Readiness Report
              </h1>
              <p className="text-slate-400 text-sm mt-2 max-w-lg">
                Generated by the Privacy-Safe Risk Abstraction Engine.
                No personal health data is accessible or exposed in this view.
              </p>
            </div>

            {/* Date + refresh */}
            <div className="flex flex-col items-end gap-2">
              <div className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-sm text-white/60">
                📅 {new Date().toLocaleDateString("en-US", {
                  weekday: "long",
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </div>
              <button
                onClick={fetchWorkplace}
                className="px-4 py-2 rounded-xl bg-pink-600/20 border border-pink-500/30 hover:bg-pink-600/30 transition text-sm font-semibold text-pink-300"
              >
                🔄 Refresh
              </button>
            </div>
          </div>
        </div>

        {/* ── Loading ── */}
        {loading && (
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 flex flex-col items-center justify-center gap-3">
            <div className="w-10 h-10 rounded-full border-4 border-pink-500/30 border-t-pink-500 animate-spin" />
            <p className="text-slate-400 text-sm">Loading readiness data...</p>
          </div>
        )}

        {/* ── Error ── */}
        {!loading && err && (
          <div className="rounded-2xl border border-red-500/30 bg-red-950/20 p-6 flex items-start gap-3">
            <span className="text-2xl">⚠️</span>
            <div>
              <div className="text-sm font-bold text-red-300">Unable to Load Report</div>
              <p className="text-xs text-red-400/70 mt-1">{err}</p>
            </div>
          </div>
        )}

        {/* ── Main content ── */}
        {!loading && data && (
          <>
            {/* Employee identity strip — name only, zero health data */}
            <div className="rounded-2xl border border-slate-800 bg-slate-900 px-6 py-4 flex items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-pink-500/20 border border-pink-500/30 flex items-center justify-center text-lg">
                  👤
                </div>
                <div>
                  <div className="text-xs text-white/30 uppercase tracking-widest">Employee</div>
                  <div className="text-lg font-bold text-white">{data.employee_name}</div>
                </div>
              </div>

              <div className="flex items-center gap-3">
                {/* Abstraction engine tag */}
                <div className="hidden sm:flex items-center gap-2 px-3 py-2 rounded-xl bg-slate-800 border border-slate-700">
                  <span className="text-sm">⚙️</span>
                  <span className="text-xs text-white/50">{data.abstraction_engine}</span>
                </div>

                {/* Health data exposed indicator */}
                <div className="flex items-center gap-2 px-3 py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
                  <span className="text-sm">🔒</span>
                  <span className="text-xs text-emerald-300 font-bold">
                    Health Data: Protected
                  </span>
                </div>
              </div>
            </div>

            {/* Top grid — Readiness badge + summary */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">

              {/* Readiness Badge — takes 1 col */}
              <div className="lg:col-span-1">
                <ReadinessBadge readiness={data.readiness} />
              </div>

              {/* Summary card — takes 2 cols */}
              <div className="lg:col-span-2 rounded-2xl border border-slate-800 bg-slate-900 p-6 flex flex-col justify-between gap-4">
                <div>
                  <div className="text-xs font-bold tracking-widest uppercase text-white/30 mb-3">
                    Engine 2.1 — Decision Summary
                  </div>
                  <h2 className="text-2xl font-extrabold text-white leading-snug">
                    {data.summary}
                  </h2>
                  <p className="text-slate-400 text-sm mt-3 leading-relaxed">
                    This summary was generated by abstracting employee wellness
                    data through the Privacy-Safe Risk Abstraction Engine.
                    No cycle, symptom, or medical data was used in producing
                    this output.
                  </p>
                </div>

                {/* Readiness meter */}
                <div>
                  <div className="flex justify-between text-xs text-white/30 mb-2">
                    <span>Low</span>
                    <span>Medium</span>
                    <span>High</span>
                  </div>
                  <div className="relative w-full h-3 rounded-full bg-slate-800">
                    {/* Track segments */}
                    <div className="absolute inset-0 flex rounded-full overflow-hidden">
                      <div className="flex-1 bg-red-500/20" />
                      <div className="flex-1 bg-yellow-500/20" />
                      <div className="flex-1 bg-emerald-500/20" />
                    </div>
                    {/* Indicator */}
                    <div
                      className={`
                        absolute top-1/2 -translate-y-1/2 w-5 h-5 rounded-full border-2 border-white shadow-lg
                        transition-all duration-700
                        ${data.readiness === "Low"
                          ? "left-[16%] bg-red-400"
                          : data.readiness === "Medium"
                          ? "left-[50%] bg-yellow-400"
                          : "left-[83%] bg-emerald-400"}
                      `}
                    />
                  </div>
                </div>

                {/* Quick stats */}
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: "Readiness", value: data.readiness, icon: "📊" },
                    { label: "Report Date", value: data.date, icon: "📅" },
                    { label: "Data Exposed", value: "None", icon: "🔒" },
                  ].map((stat, i) => (
                    <div
                      key={i}
                      className="rounded-xl border border-slate-700 bg-slate-800/50 px-3 py-3 text-center"
                    >
                      <div className="text-lg">{stat.icon}</div>
                      <div className="text-xs text-white/30 mt-1">{stat.label}</div>
                      <div className="text-sm font-bold text-white mt-0.5 truncate">
                        {stat.value}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Task Adjustments */}
            <TaskAdjustments
              adjustments={data.task_adjustments}
              readiness={data.readiness}
            />

            {/* Accommodations */}
            <Accommodations
              accommodations={data.accommodations}
              readiness={data.readiness}
            />

            {/* Privacy Shield */}
            <PrivacyShield />

          </>
        )}
      </div>
    </div>
  );
}